events:
  columns:
    [
      "id",
      "name",
      "deadline_time",
      "average_entry_score",
      "finished",
      "data_checked",
      "highest_scoring_entry",
      "deadline_time_epoch",
      "deadline_time_game_offset",
      "highest_score",
      "is_previous",
      "is_current",
      "is_next",
      "cup_leagues_created",
      "h2h_ko_matches_created",
      "chip_plays",
      "most_selected",
      "most_transferred_in",
      "top_element",
      "top_element_info",
      "transfers_made",
      "most_captained",
      "most_vice_captained",
    ]
  prep_columns: ["chip_plays", "top_element_info"]
phases:
  columns: ["id", "name", "start_event", "stop_event"]
teams:
  columns:
    [
      "code",
      "draw",
      "form",
      "id",
      "loss",
      "name",
      "played",
      "points",
      "position",
      "short_name",
      "strength",
      "team_division",
      "unavailable",
      "win",
      "strength_overall_home",
      "strength_overall_away",
      "strength_attack_home",
      "strength_attack_away",
      "strength_defence_home",
      "strength_defence_away",
      "pulse_id",
    ]
  prep_columns: ["name"]
elements:
  columns:
    [
      "chance_of_playing_next_round",
      "chance_of_playing_this_round",
      "code",
      "cost_change_event",
      "cost_change_event_fall",
      "cost_change_start",
      "cost_change_start_fall",
      "dreamteam_count",
      "element_type",
      "ep_next",
      "ep_this",
      "event_points",
      "first_name",
      "form",
      "id",
      "in_dreamteam",
      "news",
      "news_added",
      "now_cost",
      "photo",
      "points_per_game",
      "second_name",
      "selected_by_percent",
      "special",
      "squad_number",
      "status",
      "team",
      "team_code",
      "total_points",
      "transfers_in",
      "transfers_in_event",
      "transfers_out",
      "transfers_out_event",
      "value_form",
      "value_season",
      "web_name",
      "minutes",
      "goals_scored",
      "assists",
      "clean_sheets",
      "goals_conceded",
      "own_goals",
      "penalties_saved",
      "penalties_missed",
      "yellow_cards",
      "red_cards",
      "saves",
      "bonus",
      "bps",
      "influence",
      "creativity",
      "threat",
      "ict_index",
      "influence_rank",
      "influence_rank_type",
      "creativity_rank",
      "creativity_rank_type",
      "threat_rank",
      "threat_rank_type",
      "ict_index_rank",
      "ict_index_rank_type",
      "corners_and_indirect_freekicks_order",
      "corners_and_indirect_freekicks_text",
      "direct_freekicks_order",
      "direct_freekicks_text",
      "penalties_order",
      "penalties_text",
    ]
  prep_columns: ["first_name", "second_name", "web_name"]
element_stats:
  columns: ["label", "name"]
element_types:
  columns:
    [
      "id",
      "plural_name",
      "plural_name_short",
      "singular_name",
      "singular_name_short",
      "squad_select",
      "squad_min_play",
      "squad_max_play",
      "ui_shirt_specific",
      "sub_positions_locked",
      "element_count",
    ]
